# Async void Exception

This example shows, that a call to an async void method does not catch any Exceptions.